language: node_js
node_js:
- 6
- 7
- 8
addons:
  # Required to compile native modules on newer Node.js versions
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.9
    packages:
    # install toolchains
    - libmagic-dev
    - libatlas-base-dev
    - libavahi-compat-libdnssd-dev
    - libasound2-dev
    - gcc-4.8
    - g++-4.8
    - clang-3.8
    - libzmq3-dbg
    - libzmq3-dev
    - libzmq3
services:
  - mongodb
env:
  - CXX=g++-4.8
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/117063f9c1031b17e557
    on_start: never
    on_failure: change
deploy:
  provider: npm
  email: hello@mylisabox.com
  api_key:
    secure: 5h3lyk5secyEDk4Gk/Q0/wND9Xf6M53oCssy5AsM/xrclUbwIkf44f6CO2pfoPjBhQST8ZjC8J951KQooFtusREG/NmpN8j/K5sDPb8+FFD+T3mGhsaFxqFcrcbXSyKv8d3+s8qnH5vYETnRHbgjHM57JaC9JHTEMUvGiEa7mpF382vbCJCuDZm75Xnf8GIX9F89UAP8qDbFyVWYppVkbzOiiirsd0POoAQJnaa/51vWG3fmqP1dkOxajFOyrMlqXrECdifAbxyl5co0JAeWnmv4A3bthZtDLT5D3dlcP0SvH0MalGAcJ6nAQsZTqk12Qb9X1CchBLt/nvh2Y0ES/D3VLSlL7Uck4usWytUhPZ+hKyr4N811EZdkUSEP3zsLy1QFlb62xRiA5tmLp3zPeYVIFflSa7lGd/y5uaK3kiZNbDwMKLlwmNx4jvcYPwMEXmTiciqMc1B5MLFtlkArx2pyDuguildUYvKIrYau78eCnHNFm9YbHW5oBKJKKsPdwURODG6BffRcLtOhMDQfQn5CFF1f/hiXERSgnf/vyhSTkyFJ5pNI3usUzHWQpO5CLER/uHBrz9bMY/XGAJDfZyRrvfw7BetCbqS+LZ+z3LNf3KY811z2ABDAteCEEIaV6ffh+2PYnLADaY6CG8nJBb1RpM9icIq6g82TsF9S87Y=
  on:
    tags: true
    repo: mylisabox/lisa-box
    node: 7
